version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Emoji@500
      POSTGRES_DB: AYS-DB
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - '3104:3104'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ays-net

volumes:
  pgdata:

networks:
  ays-net:
    driver: bridge
