version: '3.8'

networks:
  ays-net:
    driver: bridge

services:
  # PostgreSQL Database
  db:
    image: postgres:17
    container_name: ays-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Emoji@500
      POSTGRES_DB: AYS-DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ays-net

  # NestJS Backend (with hot-reloading)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ays-backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3104
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ays-net

  # Nginx Reverse Proxy - FIXED THIS SECTION
  nginx:
    image: nginx:alpine
    container_name: ays-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/  # Changed to use local directory
    command: >
      sh -c "rm -f /etc/nginx/conf.d/default.conf
             && nginx -g 'daemon off;'"
    depends_on:
      - backend
    networks:
      - ays-net

  # PgAdmin for Database Management
  pgadmin:
   