version: '3.8'

networks:
  ays-net:
    driver: bridge

services:
   # NestJS Backend (with hot-reloading)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ays-backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3104
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ays-net
    # Add this command to run migrations on startup
    command: sh -c "npm run knex migrate:latest && npm run start:dev"

  # PostgreSQL Database
  db:
    image: postgres:17
    container_name: ays-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Emoji@500
      POSTGRES_DB: AYS-DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ays-net
    # Add health check to ensure DB is ready before migrations run
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ays-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - ays-net

  # PgAdmin for Database Management - FIXED INDENTATION
  pgadmin:
    image: dpage/pgadmin4
    container_name: ays-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ays.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - ays-net

volumes:
  postgres-data: