networks:
  ays-net:

services:
  db:
    image: postgres:17
    container_name: ays-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Emoji@500
      POSTGRES_DB: AYS-DB
    networks:
      - ays-net

  backend:
    build: .
    container_name: ays-backend
    ports:
      - "3104:3104"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ays-net
